### ISSUE TITLE
How to use retrofit converter with custom Serializers ?

### ISSUE THREAD

**Issue by anjosc** [JakeWharton/retrofit2-kotlinx-serialization-converter#59]
Hi! I'm not sure this is the correct place, but I need to specify the deserializer for a custom filtering list

When this is inside a regular class I'm able to do

```kotlin
@Serializable
data class ListWrapper(
	@Serializable(with = MySpecialListSerializer::class)
	val items : List<Something>
)
```
and have a 

```kotlin
interface Api {
	@GET("v1/listOfSomething")
	fun getListOfSomething(): Call<ListWrapper>
}
```
However I have the list returned directly as in 
```kotlin
fun getListOfSomething(): Call<List<Something>>
```
and declaring it like this, isn't picked up by retrofit / kxs converter:
```kotlin
fun getListOfSomething(): Call<@Serializable(with = MySpecialListSerializer::class) List<Transaction>>
```
How can I specify which custom Serializers to use when using retrofit with the retrofit2-kotlinx-serialization-converter ?	
Thanks !

**Comment by Mikkelet** [comment]
Yeah I'm also having problems, specifically with sealed classes.

**Comment by JakeWharton** [comment]
Annotations on the generic type parameter of the `Call` interface will be lost because Retrofit is written in Java and does not use Kotlin reflection to obtain the metadata on which that annotation is stored. As a result, you will always get effectively an un-annotated type.

A workaround would be to declare a type such as `interface SomethingList : List<Something>` which has a `@Serializable` annotation and a custom serializer which delegates to `ListSerializer(Something.serializer())`.

There is no way for this converter to work around this limitation, unfortunately. We can't even detect when it's happening to show some kind of error.
